---
namespace: splunk
name: es
authors:
  - Ansible Ecosystem Engineering team
  - Shahar Golshani <sgolshan@redhat.com>
  - Ron Gershburg <rgershbu@redhat.com>
description: Ansible Collection for Splunk Enterprise
license_file: LICENSE
tags: ["monitoring", "splunk"]
repository: https://github.com/ansible-collections/splunk.enterprise
documentation: https://github.com/ansible-collections/splunk.enterprise
homepage: https://github.com/ansible-collections/splunk.enterprise
issues: https://github.com/ansible-collections/splunk.enterprise/issues
readme: README.md
version: "1.0.0"
