---
namespace: splunk
name: enterprise
authors:
  - Ansible Ecosystem Engineering team
  - Shahar Golshani <sgolshan@redhat.com>
  - Ron Gershburg <rgershbu@redhat.com>
description: Ansible Collection for Splunk Enterprise
license_file: LICENSE
tags: ["monitoring", "splunk"]
repository: https://github.com/ansible-collections/splunk.enterprise
documentation: https://github.com/ansible-collections/splunk.enterprise
homepage: https://github.com/ansible-collections/splunk.enterprise
issues: https://github.com/ansible-collections/splunk.enterprise/issues
readme: README.md
version: "1.0.0"
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - codecov.yml
  - sonar-project.properties
  - .azure-pipelines
  - .flake8
  - .github/
  - .gitignore
  - .pre-commit-config.yaml
  - .prettierignore
  - .vscode/
  - .yamllint
